import './globals.css'
import type { Metadata } from 'next'
import ToasterContext from './context/ToasterContext'
import AuthContext from './context/AuthContext'
import Header from './components/header/Header'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='dark:bg-slate-950 bg-cyan-500'>
        <AuthContext>
          <ToasterContext />
          <Header/>
          {children}
        </AuthContext>
      </body>
    </html>
  )
}
